/**
 * Extracts the canonical prompts and rubrics from knowledge-system/ (the product spec)
 * into src/generated/knowledge.ts. The app never hand-copies prompt text.
 *
 *   npm run knowledge:sync    regenerate
 *   npm run knowledge:check   fail if the generated file is stale (runs before build)
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(__dirname, "..");
const SOURCES = {
  roleplay: "knowledge-system/prompts/roleplay-system-prompt.md",
  evaluation: "knowledge-system/prompts/evaluation-system-prompt.md",
  rubrics: "knowledge-system/04-rubrics.md",
} as const;
const OUT = join(ROOT, "src/generated/knowledge.ts");

function read(rel: string): string {
  // Normalize line endings so the hash is identical on Windows and CI.
  return readFileSync(join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");
}

/** The first ```text fenced block is the production prompt. */
function extractTextBlock(md: string, file: string): string {
  const match = md.match(/```text\n([\s\S]*?)\n```/);
  if (!match) throw new Error(`No \`\`\`text block found in ${file}`);
  return match[1];
}

/** D1–D10 band tables: from "## The 10 rubrics" up to "## Overall score". */
function extractRubrics(md: string): string {
  const start = md.indexOf("## The 10 rubrics");
  const end = md.indexOf("## Overall score");
  if (start < 0 || end < 0 || end <= start) {
    throw new Error("Rubric section markers not found in 04-rubrics.md");
  }
  return md.slice(start, end).trim();
}

export function buildKnowledgeModule(): string {
  const roleplaySrc = read(SOURCES.roleplay);
  const evaluationSrc = read(SOURCES.evaluation);
  const rubricsSrc = read(SOURCES.rubrics);

  const roleplay = extractTextBlock(roleplaySrc, SOURCES.roleplay);
  const evaluation = extractTextBlock(evaluationSrc, SOURCES.evaluation);
  const rubrics = extractRubrics(rubricsSrc);

  const hash = createHash("sha256")
    .update(roleplay)
    .update("\0")
    .update(evaluation)
    .update("\0")
    .update(rubrics)
    .digest("hex")
    .slice(0, 16);

  return `// AUTO-GENERATED by scripts/sync-knowledge.ts — do not edit.
// Sources: ${Object.values(SOURCES).join(", ")}

/** Short hash of the prompt + rubric text; stored on sessions and evaluations. */
export const KNOWLEDGE_HASH = ${JSON.stringify(hash)};

/** Prompt H — AI roleplay (prospect) system prompt template. */
export const ROLEPLAY_PROMPT_TEMPLATE = ${JSON.stringify(roleplay)};

/** Prompt I — AI evaluation (coach) system prompt template. */
export const EVALUATION_PROMPT_TEMPLATE = ${JSON.stringify(evaluation)};

/** Rubrics D1–D10 (04-rubrics.md), injected into the evaluator's <rubrics> block. */
export const RUBRICS_MARKDOWN = ${JSON.stringify(rubrics)};
`;
}

function main() {
  const next = buildKnowledgeModule();
  const check = process.argv.includes("--check");
  if (check) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== next) {
      console.error(
        "src/generated/knowledge.ts is out of date with knowledge-system/. Run `npm run knowledge:sync`.",
      );
      process.exit(1);
    }
    console.log("knowledge: up to date");
    return;
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, next);
  console.log(`knowledge: wrote ${OUT}`);
}

main();
